### ISSUE TITLE
[BUG] css issue on checkbox when focus-visible

### ISSUE THREAD

**Issue by subframe7536** [sek-consulting/solid-ui#103]
![recording](https://github.com/sek-consulting/solid-ui/assets/78338239/88f702ef-92ea-47a1-af04-1455b6e6ddf8)

`peer` should be on `CheckboxPrimitive.Input` instead of `CheckboxPrimitive.Control`

**Comment by sek-consulting** [comment]
Thanks for reporting :)
It's fixed on the next release.
