### ISSUE TITLE
Feat: configure / cli option for component path

### ISSUE THREAD

**Issue by jsimonrichard** [sek-consulting/solid-ui#106]
I'm working on a component library for one of my projects, and since this library is only for components (and the actual library files are in `./lib`), the `./src/component/ui` directory doesn't make sense.

As far as I can tell, there is no way to configure the output directory.

Obviously I can just move the file so it's not a huge issue, but it would nice if the solidui cli had an option to configure the component output directory. Or perhaps a config file could be used.

**Comment by sek-consulting** [comment]
Thanks for the feedback :)
This will be added to the list for the next PR which will focus on updating and polishing the CLI.
