### ISSUE TITLE
Popover does not work in sidebar component

### ISSUE THREAD

**Issue by AuroraLantean** [sek-consulting/solid-ui#110]
My Popover3 in my usual component works fine:
https://github.com/AuroraLantean/solidstart-shadcn-demo1/blob/dbc209e40bcfc8bdc1847c7a51de72f1b57b1673/src/components/Output.tsx#L49

But Popover1 and Popover2 in my SidebarDesktop component do not work!?
Popover1
https://github.com/AuroraLantean/solidstart-shadcn-demo1/blob/acb3eb41d6efce7377fd67d22c1df294139360cc/src/components/SidebarDesktop.tsx#L29

Popover2
https://github.com/AuroraLantean/solidstart-shadcn-demo1/blob/acb3eb41d6efce7377fd67d22c1df294139360cc/src/components/SidebarDesktop.tsx#L45

I tried changing the SidebarDesktop returned tag from `<aside>` to `<div>`, but that does not work.
What is missing? Is there certain restrictions on where to use Popover ?
Please advise. Thanks

**Comment by daelmaak** [comment]
Hey @AuroraLantean, I don't understand from your description what's wrong but I guess it doesn't open? You got to help the maintainer and meet him halfway, so could you create a minimal reproducible example or post a video of the popover not working?

**Comment by sek-consulting** [comment]
@AuroraLantean any update or a minimal repro? otherwise I would close this issue :)
