### ISSUE TITLE
Button cannot take Lucide Icon as children

### ISSUE THREAD

**Issue by AuroraLantean** [sek-consulting/solid-ui#111]
I modified the ShadCn `Button` component to show its children
```
<ButtonPrimitive.Root>
	{others.children}
</ButtonPrimitive.Root>
```
But when the children is a Lucide Icon (import { X } from "lucide-solid";), all Tailwind failed
```
<Button>
       <X size={15} />
</Button>
```

**Comment by sek-consulting** [comment]
There is no need to modify the `Button` component since the children are already shown:
```tsx
import { X } from "lucide-solid";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <Button>
      <X size={15} />
    </Button>
  );
}
```

This works just fine :)
