### ISSUE TITLE
Components missing typed exports, causing vite errors (strict requires explicit type imports, namespace imports)

### ISSUE THREAD

**Issue by T3sT3ro** [sek-consulting/solid-ui#114]
Following the [installation guide for astro](https://www.solid-ui.com/docs/installation/astro), I tried adding a `<Button>` component, but the errors started showing up as soon as I opened the editor.

First of all, this popped up in the VSCode:
```
'ValidComponent' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)
```
Which I guess stems from some kind of high strictness setting in the ts project.

So I edited the generated button component and changed (same for `PolymorphicProps`):
```diff
- import { JSX, splitProps, ValidComponent } from "solid-js"
+ import { JSX, splitProps, type ValidComponent } from "solid-js"
// and 
- import { PolymorphicProps } from "@kobalte/core/polymorphic"
+ import { type PolymorphicProps } from "@kobalte/core/polymorphic"
```

Then, when I tried launching dev server, it complained, that
```
[ERROR] [vite] The requested module 'solid-js' does not provide an export named 'JSX'
```

After navigating to the `JSX` symbol I discovered it is a namespace export, which also needs to be imported with `type`.

Right off the bat, this is the first issue that pops up when trying to create a new astro project (TS, strict) with the run off the mill component, so I imagine other components may have similar issues.

The steps taken to reproduce the issue basically follow the installation guide on the solid-ui docs website.

**Comment by sek-consulting** [comment]
Thanks for the info.
I'll look into it and hope I'll find a way to automate it with eslint or prettier.

**Comment by sek-consulting** [comment]
the fix for all the components is live 👍🏻
