### ISSUE TITLE
Navigation menu animation pop-in after the second hover

### ISSUE THREAD

**Issue by T3sT3ro** [sek-consulting/solid-ui#116]
1. Open [navigation menu demo](https://www.solid-ui.com/docs/components/navigation-menu)
2. Hover over "Getting Started" dropdown to show the menu for the first time, works as expected
3. take mouse off the "Getting Started"
4. Hover once again over "Getting Started"
5. The menu slides in from the left or something
6. now Take mouse entirely off the menu
7. Hover over the second element, "Overview"
8. The previous "Getting started" menu is opened for a split second and the "Overview" pops in immediately, causing visual flash and jump

The popup slide-in animations should behave to avoid the visual "pop" effect.

**Comment by sek-consulting** [comment]
This looks like it's a problem that's already present in the primitive:
https://kobalte.dev/docs/core/components/navigation-menu

**Comment by sek-consulting** [comment]
fixed: https://github.com/kobaltedev/kobalte/pull/456
