### ISSUE TITLE
adding OTP field doesn't add `@corvu/otp-field` package

### ISSUE THREAD

**Issue by T3sT3ro** [sek-consulting/solid-ui#117]
When adding the OTP-field component, the `@corvu/otp-field` is not added to the project and requires manual install.

**Comment by sek-consulting** [comment]
Thanks for the headsup. It's already fixed in the cli branch.
Looks like I might have to move some of the small fixes to production, since the cli update takes longer than expected unfortunatelly.

**Comment by sek-consulting** [comment]
works now :)
https://www.solid-ui.com/registry/ui/otp-field.json
