### ISSUE TITLE
Dialog closing causes "pop" by shifting several pixels left for split second

### ISSUE THREAD

**Issue by T3sT3ro** [sek-consulting/solid-ui#119]
1. Open [dialog page](https://www.solid-ui.com/docs/components/dialog)
2. Open the dialog
3. Close the dialog
4. Notice the dialog moving immediately several pixels to the left immediately after it's closed and when it's still playing closing animation.

Video (10% animations slowdown in devtools):

https://github.com/user-attachments/assets/b8d80c03-9901-4d43-b082-568c4c486e07

**Comment by sek-consulting** [comment]
This is unfortunatelly an issue of the underlying kobalte primitive.
As far as I know there is some kind of fix already in the dev branch, but not yet release. Once it's pushed an update to `@kobalte/core` solves the issue.

**Comment by sek-consulting** [comment]
fixed: https://github.com/kobaltedev/kobalte/pull/447
