### ISSUE TITLE
Website crash on search of "bar" and backspace

### ISSUE THREAD

**Issue by T3sT3ro** [sek-consulting/solid-ui#120]
docs website crashes when I try the following:
1. go to https://www.solid-ui.com/
2. open the search field
3. input "bar"
4. backspace
5. website crashes with "Error | Uncaught Client Exception" and doesn't work until refreshed

**Comment by sek-consulting** [comment]
Thanks for pointing that one out.
Unfortunatelly the error message in dev mode isn't too helpful either.
I'll see what I can do.

**Comment by sek-consulting** [comment]
fixed: https://github.com/create-signal/cmdk-solid/pull/2
