### ISSUE TITLE
Cannot read properties of null (reading 'getComputedStyle')

### ISSUE THREAD

**Issue by tutods** [sek-consulting/solid-ui#123]
Hi
I'm trying to use the carousel component with Embla, but I'm facing this error:
![image](https://github.com/user-attachments/assets/4f9affb6-0698-4272-993b-d0b6a43f6bb2)

The error only appears when I switch between routes two times, like:
- Home Page -> About Page
- About Page -> Home
- The error appears-

Already try to use `clientOnly` as people suggest me on SolidJS Discord group, but didn't work.
Any way to avoid this error without disabling SSR?

**Comment by sek-consulting** [comment]
Hi @tutods,

does this error also happen if you use the embla package by itself? Or is it a SolidUI only problem?

**Comment by tutods** [comment]
Didn't try with embla only, but I didn't install from Solid UI, only copy all login and a few styles, and the rest I implement my own styles.

**Comment by sek-consulting** [comment]
Is it possible for you to create a minimal reproducible example? Without anything just using SolidStart and SSR, 2 pages and a simple carrousel.

Thanks in advance. :)

**Comment by sek-consulting** [comment]
Any updates? :)

**Comment by tutods** [comment]
Yes, sorry for the delay.
The problem is using the [Iconify for Solid](https://iconify.design/docs/iconify-icon/solid.html), for now I'm using phosphor icons web font and apparently works.
