### ISSUE TITLE
Add support for `tailwind.prefix` config

### ISSUE THREAD

**Issue by obedm503** [sek-consulting/solid-ui#125]
`shadcn/ui` supports setting a prefix in the config. This is especially useful when integrating tailwind in legacy projects.

This is what it looks like in the `components.json`:
```json
{
  "tailwind": {
    "prefix": "tw-"
  }
}
```

My current workaround is to add the prefix to every component manually. Please add support for the tailwind prefix.

**Comment by sek-consulting** [comment]
Thanks for the suggestion :)
I'm currently in the process of rebuilding the cli so this is the perfect spot for this kind of issue/wish. 

At first I wanted to skip the prefix option but it looks like there is indeed some need.
Can you explain what the actual benefits are or how it's important for legacy projects?
