### ISSUE TITLE
Checkbox lacks indeterminate state

### ISSUE THREAD

**Issue by daelmaak** [sek-consulting/solid-ui#128]
The current [checkbox registry schema](https://github.com/sek-consulting/solid-ui/blob/main/apps/docs/src/registry/ui/checkbox.tsx) lacks an `indeterminate` state handling and icon. 

Happy to provide the PR if you pick the icon.

**Comment by sek-consulting** [comment]
Would love to see a PR if you have the time :)
I just checked the kobalte docs and saw that there is indeed an `indeterminate` state for the checkbox so it should be used.
For the icon I would go with the `minus` symbol that Chrome uses. 

```tsx
<svg  
  xmlns="http://www.w3.org/2000/svg"
   viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
  class="size-4">
  <path d="M5 12l14 0" />
</svg>
```
