### ISSUE TITLE
Hassles experienced installing to existing Vite project

### ISSUE THREAD

**Issue by AgileInteractive** [sek-consulting/solid-ui#133]
First of all, I just want to say I love the work you are all doing. I just want to chime in with my experience trying it out, I hope it can be a smoother experience in the future.

Followed [this guide](https://www.solid-ui.com/docs/installation/vite) to try to add Solid-UI to my existing project, and got into many issues:

1. It doesn't state properly that the _Edit tsconfig.json file_ step is optional. I have a vanilla js project
2. Editing vite.config.ts (well in my case vite.config.js not ts), I got error that __dirname does not exist (used chat-gpt to get it resolved)
3. After running the CLI, i got error that _tsconfig.json_ does not exist, even if i chose _no_ to Typescript
4. It deleted all the existing css in my app.css file and file was empty. Probably should also be more clear that it is the tailwinds global css that is targeted, and not other "global" css files one might have from the project.
5. It deleted all the existing config in my tailwind.config.js file and file was empty
6. After i added a button, i got the error missing _class-variance-authority_. Went to npm and installed it manually

After all this, I recovered some of the deleted stuff and decided to go to the manual section, and after trying for a while I finally got it working with a little luck.

**Comment by sek-consulting** [comment]
Thanks for your feedback! :)
The JS integration was never completely finished, but I'm currently in the process of reworking the CLI which includes finally fixing all the JS related issues.
