### ISSUE TITLE
Invalid configuration found 

### ISSUE THREAD

**Issue by wizardAEI** [sek-consulting/solid-ui#142]
![image](https://github.com/user-attachments/assets/53ca3f4e-b86a-4158-914f-c4d272f4bc81)
and this is json file（auto created before）
```json
{
  "tsx": true,
  "componentDir": "./src/components/ui",
  "tailwind": {
    "config": "tailwind.config.cjs",
    "css": "src/app.css"
  },
  "aliases": {
    "path": "~/*"
  }
}
```

**Comment by wizardAEI** [comment]
I haven't modified this file before. Could tell me if I made any mistakes?

**Comment by sek-consulting** [comment]
Hi,
looks like you're trying to use `add` with the latest version of the cli, while having a config that was created using a version `< 0.7.0`.

I changed the layout of the config to be more inline with the other frameworks and being able to provide features like js support or tailwind prefixes.

Your best option would be to delete the config an run `init` again.

**Comment by sek-consulting** [comment]
Thinking about it I really should add a check to the `add` command and a message explaining exactly what went wrong.
