### ISSUE TITLE
Navigation menu animation animation does not stop

### ISSUE THREAD

**Issue by papatie** [sek-consulting/solid-ui#143]
When hovering over the navigation menu with smaller screens, the animation does not stop and shrinks too much.

https://github.com/user-attachments/assets/98f11927-744a-4407-b2be-c976d04c7f68

**Comment by sek-consulting** [comment]
Hi @papatie,
can you reproduce this behavior with the Kobalte primitive?
https://kobalte.dev/docs/core/components/navigation-menu

I want to know if this is an Kobalte or SolidUI issue. :)

**Comment by papatie** [comment]
No I don't think so.
But the kobalt example is also not responsive. We could fix this by using different width and grid css classes as the example. ie. `w-[90vw]` but actually we would like to use full width like in the [radix-ui example](https://www.radix-ui.com/primitives/docs/components/navigation-menu)

````JSX
<NavigationMenuContent class="grid grid-rows-3 gap-3 w-[90vw] sm:grid-cols-2 sm:w-[500px] md:w-[500px] lg:w-[500px] lg:grid-cols-[.75fr_1fr] [&>li:first-child]:row-span-3">
```

**Comment by sek-consulting** [comment]
Thanks for the update :)
I should be able to fix this over the weekend since it looks like some easy changes to the example.

**Comment by sek-consulting** [comment]
fixed will be online with the next update

**Comment by papatie** [comment]
thanks!
