### ISSUE TITLE
Unclear how to use the libary.

### ISSUE THREAD

**Issue by philipp-strack** [sek-consulting/solid-ui#15]
Hello,

Thanks a lot for writing this library. One think that was unclear to me from the documentation is how to use it? Should I just copy the component, lib folder into my project? Thanks a lot for your help!

**Comment by sek-consulting** [comment]
Hi Philipp,

first of all thank you!
We're currently working on a CLI for the components to make the install process easier but we don't know when it will be ready.

For the meantime just copy the components from the github/source directly into your project.
Usually the path for this should be: "./src/components/ui/..." but if you set up your project differently just paste it into the directory where all your ui components are stored.
