### ISSUE TITLE
Is the command available ?

### ISSUE THREAD

**Issue by carere** [sek-consulting/solid-ui#20]
Hello 😄, I see on the doc that the CLI is available but it seems that it's not the case, when trying to use it with `npx`. I don't see it on npmjs.org. Is that normal ??

**Comment by coldagofee** [comment]
yeah i faced exact same issue, and end up doing manual installation

**Comment by sek-consulting** [comment]
I'm sorry for that but unfortunately we need to finish some things before we publish the cli. I Was a little bit too exited and released the docs a bit too early.

So for now it's only manual but we're working on it. :)

**Comment by carere** [comment]
No problem, just wondering if you had forgotten to click on publish 😅
