### ISSUE TITLE
CLI seems to be missing `/dist/index.mjs`

### ISSUE THREAD

**Issue by atilafassina** [sek-consulting/solid-ui#29]
Hello!! Great work!! I'm excited to try it out, but when running the init command:

```sh
pnpm dlx solidui-cli init
```

It fails with:

```sh
 WARN  Failed to create bin at .../pnpm/store/v3/tmp/dlx-75575/node_modules/.pnpm/solidui-cli@0.1.2/node_modules/solidui-cli/node_modules/.bin/suc. ENOENT: no such file or directory, open '.../pnpm/store/v3/tmp/dlx-75575/node_modules/.pnpm/solidui-cli@0.1.2/node_modules/solidui-cli/dist/index.mjs'
 WARN  Failed to create bin at .../pnpm/store/v3/tmp/dlx-75575/node_modules/.bin/suc. ENOENT: no such file or directory, open '...pnpm/store/v3/tmp/dlx-75575/node_modules/solidui-cli/dist/index.mjs'
 ENOENT  Command failed with ENOENT: suc init
```

And looking at npm, [latest release](https://www.npmjs.com/package/solidui-cli?activeTab=code) seems to really not have the whole `/dist` directory.

**Comment by sek-consulting** [comment]
Thanks for the feedback! 
Looks like I was missing a build step in the release workflow. Could you try again with the latest version (0.1.3) ?

**Comment by atilafassina** [comment]
Thanks for the quick fix!
Works like a charm now.

I just made a small PR (#32 ) to fix a tiny issue I believe I spotted! :)
