### ISSUE TITLE
docs: RadioGroup does not change state then clicking on the label

### ISSUE THREAD

**Issue by adaptive-shield-matrix** [sek-consulting/solid-ui#42]
Why is this an issue? Its very annoying as a user to specifically target the small icon instead of just clicking the label text

- does not work in official docs - https://www.solid-ui.com/docs/components/radio-group
- works in kobalte - https://kobalte.dev/docs/core/components/radio-group

It seems like the issue lies in using a `Label` instead of `RadioGroup.ItemLabel`

**Comment by sek-consulting** [comment]
Thank you! :)
Added a RadioGroupItemLabel to fix this issue.
