### ISSUE TITLE
[CLI] Something went wrong while creating your components.

### ISSUE THREAD

**Issue by xehpuk** [sek-consulting/solid-ui#48]
```
npx solidui-cli add chart
Need to install the following packages:
solidui-cli@0.3.0
Ok to proceed? (y) y
│
◇
│
■  Something went wrong while creating your components. Have you ran solidui-cli init?
```

Yes, I have.

**Comment by xehpuk** [comment]
Problem found: It's `charts`. 🙄

Maybe improve the error message?

**Comment by sek-consulting** [comment]
Thanks for the feedback. 
I really want to move away from charts.js anyway but I'm not sure when I'll have the time to do so.

But as for the error message I'll take a look.
Shouldn't be too much work to do.

**Comment by ZanzyTHEbar** [comment]
Little plug here - but i helped on the [solid-charts](https://github.com/s0ftik3/solid-chartjs) might be worth using that wrapper instead of the raw chartsjs?

**Comment by sek-consulting** [comment]
> Little plug here - but i helped on the [solid-charts](https://github.com/s0ftik3/solid-chartjs) might be worth using that wrapper instead of the raw chartsjs?

Thanks for the link. 
I'll look into it but I'm thinking about moving to apexcharts or another library cause I can't really specify the colorschema for charts.js.

**Comment by sek-consulting** [comment]
Sorry for the long delay, but I finally found the spare time to have an indepth look into the charts component and I nearly completely remade it.
The issues should be fixed now.
