### ISSUE TITLE
Issue using other tailwind plugins with this library.

### ISSUE THREAD

**Issue by ZanzyTHEbar** [sek-consulting/solid-ui#50]
I use [daisyui](https://daisyui.com) as the styling engine for most of my projects. When implementing `solid-ui` into any of those projects i get this error: 
```
[plugin:vite:css] [postcss] F:/Github/Alamanac/app/src/styles/imports.css:22:1: The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive.
```

Re-ordering my imports can remove the error, but it fails to load any css located in the file that the `solid-ui cli` generates.

Here is a [gist](https://gist.github.com/ZanzyTHEbar/9e754a57e9511847c26cd715879fb6cd).

**Comment by ZanzyTHEbar** [comment]
Note - i took the contents of `ui.presets.js` and i simply added them manually to my `tailwind.config.ts` file and the issue went away. Seems that there is an issue with the method of adding the presets to tailwind that causes the issue. I can not use `solid-ui` and `daisyui` along side each other - with a lot more granularity.

**Comment by sek-consulting** [comment]
Hi @ZanzyTHEbar,
after thinking about the whole topic and looking at other projects (shadcn/ui, shadcn-svelte, ...) I wont add support for stuff like this to the `init` function of the cli.
But I'll add a manual installation section to the docs, that walk you through the steps you need to do so you can run the `add` command afterwards.
