### ISSUE TITLE
Vanilla SolidJS project needs vite-tsconfig-paths to resolve ~/*

### ISSUE THREAD

**Issue by SilentRhetoric** [sek-consulting/solid-ui#52]
The approach of setting  `"paths": {
      "~/*": [
        "./src/*"
      ]
    }` in `tsconfig.json` does not work in a vanilla SolidJS + Vite project.  Installing `vite-tsconfig-paths` and using it as a Vite plugin resolves the issue.

Perhaps the docs could cover this, the code snippets could be set up in such a way that this paths resolution approach is not needed, or the `init` CLI command could install and configure this Vite dependency?

**Comment by sek-consulting** [comment]
Thanks for the feedback!
This will be added to the pool for the big cli overhaul I want to do the next weeks :)

**Comment by sek-consulting** [comment]
The docs now feature a step by step guide for vite that covers this exact problem:
https://www.solid-ui.com/docs/installation/vite
