### ISSUE TITLE
Review Create A Project Instructions

### ISSUE THREAD

**Issue by SilentRhetoric** [sek-consulting/solid-ui#53]
The instructions at [https://solid-ui-components.vercel.app/docs/installation](https://solid-ui-components.vercel.app/docs/installation) start a user off with the instruction to run `npx create solid@latest` which does not work on my system.  

Additionally, directing users to initialize a project with solid@latest puts them into a Beta version of Solid Start that works somewhat differently to what is currently available in other project templates and documentation in the ecosystem, which could be confusing for people.

**Comment by sek-consulting** [comment]
Thanks for the input :)
I'll update that section in the docs once I'm finished with the cli.

**Comment by stav** [comment]
$ nvm use 18
	Now using node v18.19.0 (npm v10.2.3)

	$ npx create solid@latest
	npm ERR! could not determine executable to run

	$ cat ~/.npm/_logs/2024-03-05T16_44_05_167Z-debug-0.log
	0 verbose cli /home/stav/.nvm/versions/node/v18.19.0/bin/node /home/stav/.nvm/versions/node/v18.19.0/lib/node_modules/npm/bin/npm-cli.js
	1 info using npm@10.2.3
	2 info using node@v18.19.0
	3 timing npm:load:whichnode Completed in 2ms
	4 timing config:load:defaults Completed in 1ms
	5 timing config:load:file:/home/stav/.nvm/versions/node/v18.19.0/lib/node_modules/npm/npmrc Completed in 1ms
	6 timing config:load:builtin Completed in 2ms
	7 timing config:load:cli Completed in 1ms
	8 timing config:load:env Completed in 0ms
	9 timing config:load:file:/home/stav/Work/GetStarted/Solid/.npmrc Completed in 0ms
	10 timing config:load:project Completed in 1ms
	11 timing config:load:file:/home/stav/.npmrc Completed in 0ms
	12 timing config:load:user Completed in 0ms
	13 timing config:load:file:/home/stav/.nvm/versions/node/v18.19.0/etc/npmrc Completed in 0ms
	14 timing config:load:global Completed in 0ms
	15 timing config:load:setEnvs Completed in 1ms
	16 timing config:load Completed in 6ms
	17 timing npm:load:configload Completed in 6ms
	18 timing config:load:flatten Completed in 2ms
	19 timing npm:load:mkdirpcache Completed in 0ms
	20 timing npm:load:mkdirplogs Completed in 0ms
	21 verbose title npm exec create solid@latest
	22 verbose argv "exec" "--" "create" "solid@latest"
	23 timing npm:load:setTitle Completed in 0ms
	24 timing npm:load:display Completed in 1ms
	25 verbose logfile logs-max:10 dir:/home/stav/.npm/_logs/2024-03-05T16_44_05_167Z-
	26 verbose logfile /home/stav/.npm/_logs/2024-03-05T16_44_05_167Z-debug-0.log
	27 timing npm:load:logFile Completed in 4ms
	28 timing npm:load:timers Completed in 0ms
	29 timing npm:load:configScope Completed in 0ms
	30 timing npm:load Completed in 21ms
	31 silly logfile start cleaning logs, removing 2 files
	32 timing arborist:ctor Completed in 0ms
	33 silly logfile done cleaning log files
	34 http fetch GET 200 https://registry.npmjs.org/create 277ms (cache revalidated)
	35 timing command:exec Completed in 290ms
	36 verbose stack Error: could not determine executable to run
	36 verbose stack     at getBinFromManifest (/home/stav/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
	36 verbose stack     at exec (/home/stav/.nvm/versions/node/v18.19.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:15)
	36 verbose stack     at async module.exports (/home/stav/.nvm/versions/node/v18.19.0/lib/node_modules/npm/lib/cli-entry.js:61:5)
	37 verbose pkgid create@0.0.2
	38 verbose cwd /home/stav/Work/GetStarted/Solid
	39 verbose Linux 5.15.148-2-MANJARO
	40 verbose node v18.19.0
	41 verbose npm  v10.2.3
	42 error could not determine executable to run
	43 verbose exit 1
	44 timing npm Completed in 416ms
	45 verbose code 1
	46 error A complete log of this run can be found in: /home/stav/.npm/_logs/2024-03-05T16_44_05_167Z-debug-0.log

**Comment by jmassigoge** [comment]
@stav The correct command seems to be npx create-solid@latest

**Comment by stav** [comment]
> @stav The correct command seems to be npx create-solid@latest

What the...? Ok, that works! thanks @jmassigoge

**Comment by sek-consulting** [comment]
The docs now feature 4 different installation guides :)
https://www.solid-ui.com/docs/installation/overview

If it's still missing another framework feel free to open another issue or provide a PR :)
