### ISSUE TITLE
Sheet component's closing animation is missing

### ISSUE THREAD

**Issue by declanchiu** [sek-consulting/solid-ui#68]
I realized that the closing animation of the Sheet component is missing. The sheet component in shadcn/ui has a collapsing effect when it is closed.

**Comment by declanchiu** [comment]
I took a look at the source code for solid-ui's sheet component and I think I've figured out why.

![image](https://github.com/sek-consulting/solid-ui/assets/55419399/fdb38a49-ef30-4ce6-8d64-fa1c165469d6)

Currently there is only the animate-in effect of twindcss-animate. The animate-out effect is missing。

The expand and close effects of the sheet component above shadcn/ui are controlled by the data-* property selector.

![image](https://github.com/sek-consulting/solid-ui/assets/55419399/8b95ae17-5743-45c4-bd7e-eaa3fdf29b54)

But soliid-ui's sheet component's primitive component is kobalte/Dialog, and its data-* attribute parameter is not explicitly given a value. So even if you add something like shadcn/ui's data-[epanded=true]: animatie-in, it won't work.

![Uploading image.png…]()

**Comment by declanchiu** [comment]
I think I would be interested in solving this problem and contributing a pr...  😃  

Do you have a better suggestion? @sek-consulting

**Comment by jcramb** [comment]
@declanchiu please do :) I need to fix this for my current project and would appreciate it!

**Comment by declanchiu** [comment]
> @declanchiu If you want to contribute feel free to do so :) 如果您想做出贡献，请随时这样做:)
> 
> I just merged the big changes back into the main branch so you can use that as a base without any worries.我刚刚将重大更改合并回主分支，因此您可以将其用作基础而无需担心。

Thank you for your efforts @sek-consulting  I'll try to fix this. 😄

**Comment by declanchiu** [comment]
> @declanchiu please do :) I need to fix this for my current project and would appreciate it! 请这样做:)我需要为我当前的项目解决这个问题，我将不胜感激！

Ok, I'll try to fix this, thanks for using solid-ui! 😄

**Comment by sek-consulting** [comment]
https://www.solid-ui.com/docs/components/sheet
The animation from the PR is merged and I also updated the component to be more inline with the shadcn version.
