### ISSUE TITLE
Website (solid-ui.com) is down

### ISSUE THREAD

**Issue by jcramb** [sek-consulting/solid-ui#70]
Attempting to access the docs at https://solid-ui.com or https://solid-ui-components.vercel.app/ results in a 404 error.

<img width="468" alt="Screenshot 2024-03-28 at 13 03 53" src="https://github.com/sek-consulting/solid-ui/assets/604053/ab6c1bb8-6b5c-4f46-acd9-b8edb9a635b4">

**Comment by sek-consulting** [comment]
Thanks for the info :)
Updating to solid-start 1.0 broke the vercel setup. Currently trying to fix it.

**Comment by sek-consulting** [comment]
fixed
