### ISSUE TITLE
Wrong section highlighted in side navigation in the docs

### ISSUE THREAD

**Issue by pulkitvyas08** [sek-consulting/solid-ui#78]
![image](https://github.com/sek-consulting/solid-ui/assets/54947769/5b5c9f63-cebe-4df0-afc6-e259d13a5e79)

No matter which page I open the "Alert Dialog" section is always highlighted. Moreover, the side navigation doesn't scroll down to the currently opened page's section

**Comment by sek-consulting** [comment]
Thanks for the feedback :)
I'll look into it.

**Comment by sek-consulting** [comment]
fixed :)
