### ISSUE TITLE
Provide SelectHiddenSelect out of the box

### ISSUE THREAD

**Issue by daelmaak** [sek-consulting/solid-ui#82]
I think `SelectHiddenSelect` deserves to be included in the registry for [select.tsx](https://github.com/sek-consulting/solid-ui/blob/c2e694b0966d9da6c401684934e73e5ef3582af5/apps/docs/src/registry/ui/select.tsx) since it's needed when one wants to take advantage of `FormData` on form submission. Happy to provide the PR if you agree.

**Comment by sek-consulting** [comment]
this is will be fixed in #87 :)
