### ISSUE TITLE
Support breaking changes of @kobalte/core@0.13.0

### ISSUE THREAD

**Issue by haodong404** [sek-consulting/solid-ui#84]
[@kobalte/core@0.13.0](https://github.com/kobaltedev/kobalte/releases/tag/%40kobalte%2Fcore%400.13.0) has removed Removed `asChild` and `<As/>`.
The version of `@kobalte/core` will be update to the latest every time if I add a new component.

**Comment by sek-consulting** [comment]
I'm working on it :)
For now please just fix the kobalte version in your package.json to `"@kobalte/core": "0.12.6"`
