### ISSUE TITLE
Incorrect types for button 

### ISSUE THREAD

**Issue by aellerton** [sek-consulting/solid-ui#89]
Hi there,

I've been working on a project that uses solid-start and solid-ui and, though I love them both, I keep running into issues with types and things not quite working properly.

I've created a separate public repo that can serve as a place to try out components and prove if issues are real or not:

https://github.com/aellerton/solid-issues/tree/main/solid-sek

The repo is brand new and "off the shelf", adding a `Button` component. It works, but the types aren't right:
![image](https://github.com/sek-consulting/solid-ui/assets/967842/9436674a-4558-47f4-af06-95af4dd17c5f)

Specifically: 

> Type '{ children: string; }' has no properties in common with type 'IntrinsicAttributes & ButtonProps'

Clicking on that issue I get to:

![image](https://github.com/sek-consulting/solid-ui/assets/967842/2ac475e0-eda8-4819-9048-b527d2bf5e10)

> 'index' has no exported member named 'ButtonRootProps'. Did you mean 'ButtonRootOptions'

As it's a fresh repo with vanilla everything, I'm confident this isn't something I've done in my setup.

To be clear, the demo runs fine, but the types don't seem to be quite right.

Any guidance would be most appreciated!

**Comment by aellerton** [comment]
A similar issue happens with tabs:

![image](https://github.com/sek-consulting/solid-ui/assets/967842/2e44ff1a-3d7f-4ace-bb9c-7845008d4bf1)

> Type '{ children: Element[]; class: string; }' is not assignable to type 'IntrinsicAttributes & TabsListOptions & Partial<TabsListCommonProps>'.
>   Property 'children' does not exist on type 'IntrinsicAttributes & TabsListOptions & Partial<TabsListCommonProps>'

**Comment by sek-consulting** [comment]
Looks like you're using Kobalte v0.13 which solid-ui doesn't support yet.
I'm working on updating every single component but for the meantime please set Kobalte to v0.12.6 in the package.json

**Comment by aellerton** [comment]
Thanks for that Stefan, and thanks for the great library. Your efforts are
appreciated!

I did try that but it said no such version. However, it's possible I used
0.12.7 or something silly. I'll try again later.

**Comment by aellerton** [comment]
Works nicely with 0.12.6 - thank you!
